In [ ]:
#sklearn
# Linear Regression Model

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df= pd.read_csv('iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
#y=ax+c
#:rain #testing   supervised ML
#80:20
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [ ]:
x=df.iloc[:,0:4].values # filter Independent variable


#pandas.dataset.iloc[row, column]
#df.iloc[:3] # slice your object, i.e. first three rows of your dataframe
#df.iloc[0:3] # same
#df.iloc[0, 1] # index both axis. Select the element from the first row, second column.
#df.iloc[:, 0:5] # first five columns of data frame with all rows

print(x)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
y=df.iloc[:,4].values  # filter dependent variable


#df.iloc[:,:1] select all rows and columns from 0 (included) to 1 (excluded).
#df.iloc[:,1:] select all rows and columns, but exclude column 1.
print(y)

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'V

In [ ]:
#convert Y in numbers encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder_y= LabelEncoder() 
# In this technique, each label is assigned a unique integer based on alphabetical ordering.

In [ ]:
y=labelencoder_y.fit_transform(y) #The fit_transform() method is used to fit the data into a model and transform it into a form that is more suitable for the model in a single step.

fit_transform() function only acts on training data, transform() acts on test data, and predict() acts on test data.

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
input_classes = ['audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']
label_encoder.fit(input_classes)
print ("\nClass mapping:")
for i, item in enumerate(label_encoder.classes_):
  print(item, '-->', i)


Class mapping:
audi --> 0
bmw --> 1
ford --> 2
toyota --> 3


In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
labels = ['toyota', 'ford', 'audi']
label_encoder.fit(labels)
encoded_labels = label_encoder.transform(labels)
print ("\nLabels =", labels)
print("Encoded labels =", list(encoded_labels))


Labels = ['toyota', 'ford', 'audi']
Encoded labels = [2, 1, 0]


In [ ]:
labels = ['toyota', 'ford', 'audi']
encoded_labels = label_encoder.transform(labels)
print ("\nLabels =", labels)
print("Encoded labels =", list(encoded_labels))


Labels = ['audi', 'ford', 'audi']
Encoded labels = [0, 2, 0]


In [ ]:
encoded_labels = [2, 1, 0, 3, 1]
decoded_labels = label_encoder.inverse_transform(encoded_labels)
print("\nEncoded labels =", encoded_labels)
print("Decoded labels =", list(decoded_labels))


Encoded labels = [2, 1, 0, 3, 1]
Decoded labels = ['ford', 'bmw', 'audi', 'toyota', 'bmw']


fit method - It takes the feature F and computes the mean (μ) and standard deviation (σ) of feature F. 



The fit() method helps in fitting the training dataset into an estimator (ML algorithms).
The transform() helps in transforming the data into a more suitable form for the model.
The fit_transform() method combines the functionalities of both fit() and transform().


In [ ]:
from sklearn.model_selection import train_test_split 


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
#x-Feature of input Data
#y - Target
#shuffle - The shuffle parameter controls whether the input dataset is randomly shuffled before being split into train and test data.
#The random_state parameter controls how the pseudo-random number generator randomly selects observations to go into the training set or test set.

By default, this is set to shuffle = True. What that means, is that by default, the data are shuffled into random order before splitting, so the observations will be allocated to the training and test data randomly.

If you set shuffle = False, random sorting will be turned off, and the data will be split in the order the data are already in.

If you set shuffle = False, then you must set stratify = None.

In [ ]:
x_train

array([[6.2, 3.4, 5.4, 2.3],
       [4.4, 3.2, 1.3, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.6, 3. , 4.1, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3. , 5. , 1.7],
       [6.8, 2.8, 4.8, 1.4],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.4, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.4, 3.7, 1.5, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.2, 2.8, 4.8, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6. , 3.4, 4.5, 1.6],
       [6. , 2.9, 4.5, 1.5],
       [5.9, 3. , 5.1, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.2, 2

In [ ]:
x_train.size

420

In [ ]:
x_test.size

180

In [ ]:
y_train.size

105

In [ ]:
y_test.size

45

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#Create LogisticRegression object
logmodel=LogisticRegression()

# Train the model using the training sets
logmodel.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred= logmodel.predict(x_test) #given a trained model, predict the label of a new set of data.

In [ ]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [ ]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 12,  1],
       [ 0,  2, 15]])

In [ ]:
(28/30)*100

93.33333333333333

In [ ]:
logmodel.score(x_test,y_test)

0.9333333333333333

In [ ]:
from sklearn.neighbors import KNeighborsClassifier  


In [ ]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) # distance name

In [ ]:
classifier_knn.fit(x_train,y_train) # model training 70:30

KNeighborsClassifier()

In [ ]:
y_pred_knn=classifier_knn.predict(x_test)

In [ ]:
y_pred_knn

array([2, 2, 2, 0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 1, 0, 1, 2, 2, 1, 0,
       2])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred_knn)

array([[15,  0,  0],
       [ 0, 12,  1],
       [ 0,  1, 16]])

In [ ]:
classifier_knn.score(x_test,y_test)

0.9555555555555556

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9555555555555556

In [ ]:
# NaiveBias Model

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
classifier_nb= GaussianNB()

In [ ]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred= classifier_nb.predict(x_test)

In [ ]:
y_pred

array([2, 2, 2, 0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0, 1, 0, 1,
       2, 1, 0, 0, 2, 1, 0, 1, 2, 0, 1, 2, 0, 0, 2, 1, 0, 1, 2, 2, 1, 0,
       1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9555555555555556

In [ ]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 13,  0],
       [ 0,  3, 14]])

In [ ]:
classifier_nb.score(x_test,y_test)

0.9333333333333333

The fit(data) method is used to compute the mean and std dev for a given feature to be used further for scaling.
The transform(data) method is used to perform scaling using mean and std dev calculated using the .fit() method.
The fit_transform() method does both fits and transform.